### PR TITLE
Add a link to the account page.

### PR DESCRIPTION
**Pull request by JulienPalard**
Which is not obvious, I searched in admin.gandi.net for a bunch of
minutes before finding account.gandi.net.

### CODE REVIEW

**Comment by JulienPalard** [comment]
Damned, it's more complicated than that. The account.gandi.net interface tells:

> Votre nouvelle clef d'API est :

without telling if it's the `xmlrpc api` or `apirest` key.

Trying to set it as `apirest` key and running `gandi domain list` I get:

>  No configuration found, please use 'gandi setup' command

Trying to set it as `api` key and running `gandi domain list` I get:

> Invalid API key, please use 'gandi setup' command.

so there's something that `gandi setup` should tell to clarify that, my PR is not enough. Do anyone know?

**Comment by akaihola** [comment]
@JulienPalard, see also #305.

**Comment by JulienPalard** [comment]
It should be better now, I was able to query using my own instructions, but as I don't have a v4 key I only have access to:

```
 $ gandi dns create
 $ gandi dns delete
 $ gandi dns domain.list
 $ gandi dns list
 $ gandi dns keys create
 $ gandi dns keys delete
 $ gandi dns keys info
 $ gandi dns keys list
 $ gandi dns keys recover
```

**Review by yanndinendal — APPROVED** [review]

**Comment by yanndinendal** [comment]
Thanks :)

**Pull request merged**
